# SKALAR-YEAR
SELECT
    NOPEMBAYARAN,
    YEAR(TANGGAL_PEMBAYARAN)
FROM
    hukuman
WHERE
    YEAR(TANGGAL_PEMBAYARAN) > 1995;
#SKALAR-CONCAT
SELECT
    NOPEMAIN,
    CONCAT(LEFT(INISIAL, 1), '.', NAMA) AS NAMA_BARU
FROM
    pemain
WHERE
    LEFT(NAMA, 1) = 'R';
#SKALAR-COALESCE
SELECT
    INISIAL,
    NAMA, COALESCE(NOLIGA, '1')
FROM
    pemain;
#SKALAR-D
SELECT
    NOPEMAIN,
    DAYNAME(TANGGAL_LAHIR),
    MONTHNAME(TANGGAL_LAHIR),
    DAYOFYEAR(TANGGAL_LAHIR)
FROM
    pemain
WHERE
    NOPEMAIN < 10;